[package]
name = "neovim-calculator"
version = "0.1.0"
authors = ["louvre2489 <louvre2489@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neovim-lib = "0.6.0"
